### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by vishal-h** [marcelotto/panpipe#1]
Is it possible to add PDF support? Basically convert html,docx etc to pdf

**Comment by marcelotto** [comment]
This library is just a wrapper around Pandoc. So you can use any of its various ways for PDF conversion (pdflatex, xelatex, lualatex, pdfroff, wkhtml2pdf, prince, or weasyprint). Please have a look at the Pandoc documentation and then on the Panpipe README to see how it is mapped to Elixir.
