### ISSUE TITLE
syntax for --variables with KEY[=VAL] or KEY[:VAL]

### ISSUE THREAD

**Issue by shotleybuilder** [marcelotto/panpipe#2]
An example for handling variables might be useful in the ReadMe.  I had to peek into the code to understand what might work :)
`Panpipe.pandoc( input: "input.md", from: {:markdown, [:emoji]}, output: "output.pdf", to: :pdf, pdf_engine: :xelatex, variable: :"linkcolor=blue" )`

**Comment by marcelotto** [comment]
This section of the README should have explained it:

> Pandoc can be called with the Panpipe.pandoc/2 function. Generally it takes the long-form arguments of Pandoc as the usual Keyword list options with dashes replaced by underscores

I'll try to make it more clear.

But you should be able to pass the key-value pair for the variable as a string or did you experience any problems with that?

BTW: `pdf` is not a valid output format (at least in my Pandoc version, which is 2.7.3), you should use `latex` in this case.
